services:
  - type: web
    name: grano-sabor-api
    env: python
    buildCommand: |
      pip install -r requirements.txt
      npm ci || npm install
      npm run build:css
    startCommand: python run.py
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: POST_DEPLOY_RESTORE
        value: true
      - key: POST_DEPLOY_FORCE
        value: false
      - key: AUTO_RESTORE_ON_EMPTY
        value: true
      - key: FORCE_ADMIN_CREATION
        value: true
      - key: ENABLE_RLS
        value: true
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: ADMIN_USERNAME
        fromDatabase:
          name: postgres
          property: user
      - key: ADMIN_PASSWORD
        fromDatabase:
          name: postgres
          property: password
      - key: POSTGRES_USER
        fromDatabase:
          name: postgres
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: postgres
          property: password
      - key: POSTGRES_DB
        fromDatabase:
          name: postgres
          property: database
      - key: POSTGRES_SERVER
        fromDatabase:
          name: postgres
          property: host
      - key: POSTGRES_PORT
        fromDatabase:
          name: postgres
          property: port
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: JWT_SECRET_KEY
        sync: false
      # Las variables para filebase deben configurarse manualmente en Render
      - key: FILEBASE_KEY
        sync: false
      - key: FILEBASE_SECRET
        sync: false
      - key: FILEBASE_BUCKET
        sync: false
      # Variables para la restauración automática desde GitHub
      - key: GITHUB_BACKUP_URL
        sync: false
      - key: GITHUB_TOKEN
        sync: false

databases:
  - name: postgres
    databaseName: granosabor
    user: granosabor
    plan: free
