name: Backup Database

on:
  # Ejecutar cada día a las 2am
  schedule:
    - cron: '0 2 * * *'
  
  # Permitir ejecución manual desde la interfaz de GitHub
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout código
        uses: actions/checkout@v3
      
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Configurar variables de entorno
        run: |
          echo "ENVIRONMENT=ci" >> $GITHUB_ENV
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV
          echo "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}" >> $GITHUB_ENV
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> $GITHUB_ENV
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> $GITHUB_ENV
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> $GITHUB_ENV
          echo "POSTGRES_SERVER=${{ secrets.POSTGRES_SERVER }}" >> $GITHUB_ENV
          echo "POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}" >> $GITHUB_ENV
          echo "ADMIN_USERNAME=${{ secrets.ADMIN_USERNAME }}" >> $GITHUB_ENV
          echo "ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }}" >> $GITHUB_ENV
      
      - name: Crear backup
        run: python -m scripts.backup_database --create
      
      - name: Subir backup como Release
        uses: softprops/action-gh-release@v1
        with:
          files: backups/*.zip
          name: "Backup DB ${{ github.run_number }} - ${{ github.event.repository.updated_at }}"
          tag_name: "backup-${{ github.run_number }}"
          body: "Backup automático de la base de datos"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Subir backup como artefacto
        uses: actions/upload-artifact@v3
        with:
          name: database-backup
          path: backups/*.zip
          retention-days: 30
