name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  test-and-migrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest --maxfail=1 --disable-warnings -q

      - uses: supabase/setup-cli@v1
        with:
          version: "latest"

      - name: Apply Supabase migrations
        run: supabase db push --db-url "${{ secrets.SUPABASE_DB_URL }}"

  deploy:
    needs: test-and-migrate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Trigger Render deployment
        uses: bounceapp/render-action@0.12.0
        with:
          render-token: ${{ secrets.RENDER_TOKEN }}
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
