name: Database Backup

on:
  schedule:
    # Ejecutar a las 00:00 todos los días
    - cron: "0 0 * * *"
  # También permitir ejecución manual
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create database backup
        run: python scripts/db_utils/database_backup.py backup
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          ENVIRONMENT: production

      - name: Zip backup files
        run: |
          BACKUP_DIR=$(ls -td backups/* | head -1)
          echo "Compressing backup: $BACKUP_DIR"
          zip -r "$BACKUP_DIR.zip" "$BACKUP_DIR"

      - name: Upload backup as artifact
        uses: actions/upload-artifact@v3
        with:
          name: database-backup
          path: backups/*.zip
          retention-days: 14 # Guardar durante 14 días


      # Opcional: Subir el backup a un servicio de almacenamiento
      # (AWS S3, Google Cloud Storage, etc.)
